package main

import (
	"fmt"
	"net/http"
	"os"

	"log" // "github.com/cihub/seelog"
)

// const (
//     DB_USER     = "postgres"
//     DB_PASSWORD = "postgres"
//     DB_LOCATION = "localhost"
//     DB_NAME     = "postgres"
//     DB_SSLMODE  = "disable"
// )

const (
	DB_USER     = "u311d07be533d42da8c704a4c29f0d573"
	DB_PASSWORD = "c9e75db43e744176a5970138c3b7f080"
	DB_LOCATION = "10.72.6.110:5432"
	DB_NAME     = "d311d07be533d42da8c704a4c29f0d573"
	DB_SSLMODE  = "disable" //verify-full"
)

const (
	DEFAULT_PORT = "9000"
)

func HomeHandler(w http.ResponseWriter, r *http.Request) {
	log.Println("HomeHandler Starting")
	//fmt.Fprintln(w, "Hello, GO World!n")
	fmt.Fprintln(w, "#EXTM3U")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,About Script")
	fmt.Fprintln(w, "http://on.meshra.com/tiptv/about.wmv")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Angel TV")
	fmt.Fprintln(w, "http://doh57iesfegop.cloudfront.net/angeltv/angeltvindia600/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Madha TV")
	fmt.Fprintln(w, "rtmp://103.49.238.70:1935/madhatv/_definst_playpath=mp4:myStream_source swfUrl=http://p.jwpcdn.com/player/v/7.2.2/jwplayer.flash.swf pageUrl=http://madha.tv/live-player.php")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Anboli TV")
	fmt.Fprintln(w, "rtmp://38.96.148.172:1935/live/ playpath=anboli swfUrl=http://live.akamain.info/player/jw6/jwplayer/jwplayer.flash.swf pageUrl=http://live.akamain.info/player/files/anboli/index.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Sri Sankara TV")
	fmt.Fprintln(w, "rtmp://live.wmncdn.net/srisankaratv1/ playpath=986995610b14c8529ce441b18236d4c7.sdp swfUrl=http://player-apac-sing.webmobilive.com/player/liveplayer.swf pageUrl=http://www.srisankaratv.com/watchtv.php")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,News 7 Tamil")
	fmt.Fprintln(w, "http://d2voe16cs5psaw.cloudfront.net/news7new/smil:news7new.smil/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Athavan TV")
	fmt.Fprintln(w, "http://play-fs.amgiptv.com/vxtvathavan/athavantvlive.stream/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,EET TV")
	fmt.Fprintln(w, "http://37.59.17.222:1935/live_ca/eettv/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Arra TV")
	fmt.Fprintln(w, "http://arratvcloud.purplestream.in/arratvorg/smil:arratv.smil/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Imayam TV")
	fmt.Fprintln(w, "rtmp://38.96.148.172:1935/live/ playpath=imayamtv swfUrl=http://live.akamain.info/v1/imayamtv/jwplayer/jwplayer.flash.swf pageUrl=http://live.akamain.info/v1/imayamtv/index.html live=1")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Lotus News")
	fmt.Fprintln(w, "http://118.102.228.195:1935/live/stream/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Puthiya Thalaimurai")
	fmt.Fprintln(w, "http://dzamqgwxt2cln.cloudfront.net/ngmedia/ptm_400/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Puthuyugam")
	fmt.Fprintln(w, "http://d211bpuke56xnv.cloudfront.net/ngmedia/pym_400/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vasantham TV")
	fmt.Fprintln(w, "http://cdncities.com/vasanthamtv/vasanthamtv/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Dheeran TV")
	fmt.Fprintln(w, "http://edgecastdheerantv.purplestream.in/dheeranorg/ngrp:dheeran_all/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Thanthi TV")
	fmt.Fprintln(w, "http://edgecastthanthitv.purplestream.in/httporg/ngrp:thanthi_all/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vimbam TV")
	fmt.Fprintln(w, "rtmp://91.219.43.148:1935/vimbamtv/ playpath=vimbamtv swfUrl=http://p.jwpcdn.com/6/12/jwplayer.flash.swf pageUrl=http://www.vimbamtv.com/movie.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vendhar TV")
	fmt.Fprintln(w, "rtmp://45.79.203.234:1935/vendhar/ playpath=myStream swfUrl=http://vendharmedia.in/video-js.swf pageUrl=http://vendharmedia.in/")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,IBC Tamil")
	fmt.Fprintln(w, "http://ibctamil.zecast.net/ibctamil/smil:ibctamil.smil/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vasanth TV")
	fmt.Fprintln(w, "http://vasanth.live.cdn.bitgravity.com/vasanth/secure/live/feed01?e=0%26h=a9be0836bc39f96d0a9a958a659dfc1d%26bgsecuredir=1&amp;autoPlay=true")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Makkal TV")
	fmt.Fprintln(w, "http://edgecastmakkaltv.purplestream.in/makkalorg/ngrp:makkaltv_all/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Masala TV")
	fmt.Fprintln(w, "rtmp://188.166.127.249/masalatv/ playpath=myStream swfUrl=http://www.mediaworldasia.dk/media/yendifvideoshare/player/player.swf?1462632676628 pageUrl=http://www.mediaworldasia.dk/index.php?option=com_yendifvideoshare&amp;view=video&amp;id=124&amp;tmpl=component")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,TTN Tamil Oli")
	fmt.Fprintln(w, "http://166.62.121.101:1935/ttn/ttn/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vanavil Plus")
	fmt.Fprintln(w, "rtmp://server.maxwellstreaming.com/vanavil playpath=myStream swfUrl=http://www.maxwellstreaming.com/player.swf pageUrl=http://www.vanaviltv.in/live.php")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,DD Podhigai")
	fmt.Fprintln(w, "rtmp://live-fs.wmncdn.net/ddpodigailive1/ playpath=live1.stream swfUrl=http://p.jwpcdn.com/6/12/jwplayer.flash.swf pageUrl=http://www.ddpodhigai.org.in/live.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Kathir TV")
	fmt.Fprintln(w, "rtmp://server.maxwellstreaming.com:1935/kathir playpath=myStream swfUrl=http://www.livewebcast.in/jwplayer/player.swf pageUrl=http://kathirtv.com/livetv/")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Saras TV")
	fmt.Fprintln(w, "http://live.streamjo.com:1935/sarastv/sarastv/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,1Yes TV")
	fmt.Fprintln(w, "http://stream.mslive.in:1967/live/gd416/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Tamil Biz TV")
	fmt.Fprintln(w, "rtmp://rtmp.santhoratv.zecast.net/tamilbusinesstv// playpath=tamilbusinesstv swfUrl=http://p.jwpcdn.com/6/12/jwplayer.flash.swf pageUrl=http://livetvchannelsfree.com/tamilbusinesstv.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Santhora TV")
	fmt.Fprintln(w, "http://santhoratv.zecast.net/santhoratv/santhoratv/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Peppers TV")
	fmt.Fprintln(w, "rtmp://live.wmncdn.net/pepperstv/ playpath=51f5cdae2cc7bd5e4e8e76b7357ae0f8.sdp swfUrl=http://p.jwpcdn.com/6/12/jwplayer.flash.swf pageUrl=http://livetvchannelsfree.com/pepperstv.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Test 01")
	fmt.Fprintln(w, "http://mobile.amgiptv.com/vxtvlqkalaingertv/kalaingertvlq.stream/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Test 02")
	fmt.Fprintln(w, "http://play-fs.amgiptv.com/vxtvmegatv/megatv.stream/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Test 03")
	fmt.Fprintln(w, "http://50.7.1.178/india_iptv/sunmusicINDIA/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Vanavil FM (R)")
	fmt.Fprintln(w, "http://s1.yesstreaming.net:9000/:stream/1")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Mukil FM (R)")
	fmt.Fprintln(w, "http://live64.jiljilradio.com/;stream1.mp3")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Kalasam FM (R)")
	fmt.Fprintln(w, "http://live.kalasam.com:8084")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,LankaSri FM (R)")
	fmt.Fprintln(w, "http://media2.lankasri.fm")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Oli 96.8 FM (R)")
	fmt.Fprintln(w, "http://mediacorp.rastream.com/968fm?type=.flv")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Oli 96.8 FM (R)")
	fmt.Fprintln(w, "http://mediacorp.rastream.com/968fm?type=.flv")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,THR Raaga (R)")
	fmt.Fprintln(w, "http://astro3.rastream.com:80/raaga?type=.flv")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,ETR FM (R)")
	fmt.Fprintln(w, "http://cast2.serverhostingcenter.com:8646/stream")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Puradsi FM (R)")
	fmt.Fprintln(w, "http://puradsifm.net:9994")
	log.Println("HomeHandler Ending")
}

func V1Handler(w http.ResponseWriter, r *http.Request) {
	log.Println("HomeHandler Starting")
	//fmt.Fprintln(w, "Hello, GO World!n")
	fmt.Fprintln(w, "#EXTM3U")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Sri Sankara TV")
	fmt.Fprintln(w, "rtmp://live.wmncdn.net/srisankaratv1/ playpath=986995610b14c8529ce441b18236d4c7.sdp swfUrl=http://player-apac-sing.webmobilive.com/player/liveplayer.swf pageUrl=http://www.srisankaratv.com/watchtv.php")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,News 7 Tamil")
	fmt.Fprintln(w, "http://d2voe16cs5psaw.cloudfront.net/news7new/smil:news7new.smil/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Athavan TV")
	fmt.Fprintln(w, "http://play-fs.amgiptv.com/vxtvathavan/athavantvlive.stream/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,EET TV")
	fmt.Fprintln(w, "http://37.59.17.222:1935/live_ca/eettv/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Arra TV")
	fmt.Fprintln(w, "http://arratvcloud.purplestream.in/arratvorg/smil:arratv.smil/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Imayam TV")
	fmt.Fprintln(w, "rtmp://38.96.148.172:1935/live/ playpath=imayamtv swfUrl=http://live.akamain.info/v1/imayamtv/jwplayer/jwplayer.flash.swf pageUrl=http://live.akamain.info/v1/imayamtv/index.html live=1")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Lotus News")
	fmt.Fprintln(w, "http://118.102.228.195:1935/live/stream/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Puthiya Thalaimurai")
	fmt.Fprintln(w, "http://dzamqgwxt2cln.cloudfront.net/ngmedia/ptm_400/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Puthuyugam")
	fmt.Fprintln(w, "http://d211bpuke56xnv.cloudfront.net/ngmedia/pym_400/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vasantham TV")
	fmt.Fprintln(w, "http://cdncities.com/vasanthamtv/vasanthamtv/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Dheeran TV")
	fmt.Fprintln(w, "http://edgecastdheerantv.purplestream.in/dheeranorg/ngrp:dheeran_all/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Thanthi TV")
	fmt.Fprintln(w, "http://edgecastthanthitv.purplestream.in/httporg/ngrp:thanthi_all/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vimbam TV")
	fmt.Fprintln(w, "rtmp://91.219.43.148:1935/vimbamtv/ playpath=vimbamtv swfUrl=http://p.jwpcdn.com/6/12/jwplayer.flash.swf pageUrl=http://www.vimbamtv.com/movie.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vendhar TV")
	fmt.Fprintln(w, "rtmp://45.79.203.234:1935/vendhar/ playpath=myStream swfUrl=http://vendharmedia.in/video-js.swf pageUrl=http://vendharmedia.in/")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,IBC Tamil")
	fmt.Fprintln(w, "http://ibctamil.zecast.net/ibctamil/smil:ibctamil.smil/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vasanth TV")
	fmt.Fprintln(w, "http://vasanth.live.cdn.bitgravity.com/vasanth/secure/live/feed01?e=0%26h=a9be0836bc39f96d0a9a958a659dfc1d%26bgsecuredir=1&amp;autoPlay=true")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Makkal TV")
	fmt.Fprintln(w, "http://edgecastmakkaltv.purplestream.in/makkalorg/ngrp:makkaltv_all/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Masala TV")
	fmt.Fprintln(w, "rtmp://188.166.127.249/masalatv/ playpath=myStream swfUrl=http://www.mediaworldasia.dk/media/yendifvideoshare/player/player.swf?1462632676628 pageUrl=http://www.mediaworldasia.dk/index.php?option=com_yendifvideoshare&amp;view=video&amp;id=124&amp;tmpl=component")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,TTN Tamil Oli")
	fmt.Fprintln(w, "http://166.62.121.101:1935/ttn/ttn/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Vanavil Plus")
	fmt.Fprintln(w, "rtmp://server.maxwellstreaming.com/vanavil playpath=myStream swfUrl=http://www.maxwellstreaming.com/player.swf pageUrl=http://www.vanaviltv.in/live.php")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,DD Podhigai")
	fmt.Fprintln(w, "rtmp://live-fs.wmncdn.net/ddpodigailive1/ playpath=live1.stream swfUrl=http://p.jwpcdn.com/6/12/jwplayer.flash.swf pageUrl=http://www.ddpodhigai.org.in/live.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Kathir TV")
	fmt.Fprintln(w, "rtmp://server.maxwellstreaming.com:1935/kathir playpath=myStream swfUrl=http://www.livewebcast.in/jwplayer/player.swf pageUrl=http://kathirtv.com/livetv/")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Saras TV")
	fmt.Fprintln(w, "http://live.streamjo.com:1935/sarastv/sarastv/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,1Yes TV")
	fmt.Fprintln(w, "http://stream.mslive.in:1967/live/gd416/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Tamil Biz TV")
	fmt.Fprintln(w, "rtmp://rtmp.santhoratv.zecast.net/tamilbusinesstv// playpath=tamilbusinesstv swfUrl=http://p.jwpcdn.com/6/12/jwplayer.flash.swf pageUrl=http://livetvchannelsfree.com/tamilbusinesstv.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Santhora TV")
	fmt.Fprintln(w, "http://santhoratv.zecast.net/santhoratv/santhoratv/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Peppers TV")
	fmt.Fprintln(w, "rtmp://live.wmncdn.net/pepperstv/ playpath=51f5cdae2cc7bd5e4e8e76b7357ae0f8.sdp swfUrl=http://p.jwpcdn.com/6/12/jwplayer.flash.swf pageUrl=http://livetvchannelsfree.com/pepperstv.html")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Test 01")
	fmt.Fprintln(w, "http://mobile.amgiptv.com/vxtvlqkalaingertv/kalaingertvlq.stream/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Test 02")
	fmt.Fprintln(w, "http://play-fs.amgiptv.com/vxtvmegatv/megatv.stream/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil TV,Test 03")
	fmt.Fprintln(w, "http://50.7.1.178/india_iptv/sunmusicINDIA/playlist.m3u8")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Vanavil FM (R)")
	fmt.Fprintln(w, "http://s1.yesstreaming.net:9000/:stream/1")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Mukil FM (R)")
	fmt.Fprintln(w, "http://live64.jiljilradio.com/;stream1.mp3")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Kalasam FM (R)")
	fmt.Fprintln(w, "http://live.kalasam.com:8084")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,LankaSri FM (R)")
	fmt.Fprintln(w, "http://media2.lankasri.fm")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Oli 96.8 FM (R)")
	fmt.Fprintln(w, "http://mediacorp.rastream.com/968fm?type=.flv")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Oli 96.8 FM (R)")
	fmt.Fprintln(w, "http://mediacorp.rastream.com/968fm?type=.flv")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,THR Raaga (R)")
	fmt.Fprintln(w, "http://astro3.rastream.com:80/raaga?type=.flv")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,ETR FM (R)")
	fmt.Fprintln(w, "http://cast2.serverhostingcenter.com:8646/stream")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "#EXTINF:-1 group-title=Tamil Radio,Puradsi FM (R)")
	fmt.Fprintln(w, "http://puradsifm.net:9994")
	log.Println("HomeHandler Ending")
}

func main() {
	// defer log.Flush()
	log.Println("App Started")
	fmt.Println("App started")

	// router := mux.NewRouter()
	// router.HandleFunc("/", HomeHandler)
	// router.HandleFunc("/db", DBHandler)
	// // Bind to a port and pass our router in
	// http.ListenAndServe(":8000", nil)

	var port string
	if port = os.Getenv("PORT"); len(port) == 0 {
		log.Println("Warning, PORT not set. Defaulting to %+vn", DEFAULT_PORT)
		port = DEFAULT_PORT
	}
	//	port = DEFAULT_PORT

	http.HandleFunc("/", HomeHandler)
	http.HandleFunc("/v1", V1Handler)

	err := http.ListenAndServe(":"+port, nil)
	if err != nil {
		log.Println("ListenAndServe: ", err)
	}

}
